/**
 * FileUpload Component
 * Handles CSV file upload and parsing
 */

import React, { useCallback } from 'react';
import { Upload } from 'lucide-react';

interface FileUploadProps {
  onFileUpload: (file: File) => void;
  isLoading: boolean;
}

const FileUpload: React.FC<FileUploadProps> = ({ onFileUpload, isLoading }) => {
  const handleFileChange = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file && file.type === 'text/csv') {
      onFileUpload(file);
    } else {
      alert('Please select a valid CSV file');
    }
  }, [onFileUpload]);

  const handleDrop = useCallback((event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    const file = event.dataTransfer.files[0];
    if (file && file.type === 'text/csv') {
      onFileUpload(file);
    } else {
      alert('Please drop a valid CSV file');
    }
  }, [onFileUpload]);

  const handleDragOver = useCallback((event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
  }, []);

  return (
    <div className="file-upload-container">
      <div
        className={`file-upload-area ${isLoading ? 'loading' : ''}`}
        onDrop={handleDrop}
        onDragOver={handleDragOver}
      >
        <div className="upload-content">
          {isLoading ? (
            <>
              <div className="spinner" />
              <p>Processing CSV file...</p>
            </>
          ) : (
            <>
              <Upload size={48} className="upload-icon" />
              <h3>Upload Property Data</h3>
              <p>Drag and drop your CSV file here, or click to browse</p>
              <input
                type="file"
                accept=".csv"
                onChange={handleFileChange}
                className="file-input"
                disabled={isLoading}
              />
              <button className="browse-button" disabled={isLoading}>
                Browse Files
              </button>
            </>
          )}
        </div>
      </div>
      
      <div className="upload-instructions">
        <h4>Instructions:</h4>
        <ul>
          <li>Upload a CSV file generated by the Rightmove scraper</li>
          <li>File should contain columns like: address, price, bedrooms, property_size_sqm, etc.</li>
          <li>Supported format: CSV with headers</li>
        </ul>
      </div>
    </div>
  );
};

export default FileUpload;
